// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIpWnauxpK1Bt_Ixr3-jtc6Gxmuspd04U',
    appId: '1:634890407202:web:4e7ed66a4c0ebb4cf0297b',
    messagingSenderId: '634890407202',
    projectId: 'crop-iq',
    authDomain: 'crop-iq.firebaseapp.com',
    storageBucket: 'crop-iq.firebasestorage.app',
    measurementId: 'G-LECLLGW8DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoHjl2LvKR_hvgKHz3woGTALiIo0gL3kk',
    appId: '1:634890407202:android:dbaf4912cda9dd82f0297b',
    messagingSenderId: '634890407202',
    projectId: 'crop-iq',
    storageBucket: 'crop-iq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4RzZiF-LRmGDtDyZ4iCO7SHVj8ZMLpwA',
    appId: '1:634890407202:ios:c77c8404baa598e2f0297b',
    messagingSenderId: '634890407202',
    projectId: 'crop-iq',
    storageBucket: 'crop-iq.firebasestorage.app',
    iosBundleId: 'com.example.cropIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4RzZiF-LRmGDtDyZ4iCO7SHVj8ZMLpwA',
    appId: '1:634890407202:ios:c77c8404baa598e2f0297b',
    messagingSenderId: '634890407202',
    projectId: 'crop-iq',
    storageBucket: 'crop-iq.firebasestorage.app',
    iosBundleId: 'com.example.cropIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIpWnauxpK1Bt_Ixr3-jtc6Gxmuspd04U',
    appId: '1:634890407202:web:0cc14fe33e0068b0f0297b',
    messagingSenderId: '634890407202',
    projectId: 'crop-iq',
    authDomain: 'crop-iq.firebaseapp.com',
    storageBucket: 'crop-iq.firebasestorage.app',
    measurementId: 'G-TWTW9CW5X3',
  );
}
